### ISSUE TITLE
Yarn Berry 사용 관련

### ISSUE THREAD

**Issue by lekakid** [lekakid/ArcaRefresher#109]
@green1052 
#104 관련해서 최근에 코드 작업하다보니 문제가 확인되어서 의논을 좀 하려고 합니다.
PR 받을 당시에는 빌드 테스트 정도만 했던터라 확인을 못했던 부분입니다.

## VSCode 환경에서 모듈의 타입 정보를 읽어오지 못하는 문제
![image](https://user-images.githubusercontent.com/1362809/217997812-944309f0-975a-4e3c-9c87-76b0f9ee0aab.png)
본래라면 위처럼 인텔리센스가 동작합니다만, yarn berry pnp 적용 이후로는 react 이외의 패키지에 대해서는 아무것도 나오지 않아서 곤란합니다. 컴포넌트에 무슨 속성이 있는지 조차 나오지 않고 prop-types에 따른 타입 검사도 안되는 중입니다.

## ESLint config 패키지 간 충돌 문제
```Bash
[Error - 1:12:15 PM] Error: Plugin "import" was conflicted between ".eslintrc.js » eslint-config-airbnb » C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\__virtual__\eslint-config-airbnb-base-virtual-6d1dd3fb6b\0\cache\eslint-config-airbnb-base-npm-15.0.0-802837dd26-38626bad2c.zip\node_modules\eslint-config-airbnb-base\index.js » C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\__virtual__\eslint-config-airbnb-base-virtual-6d1dd3fb6b\0\cache\eslint-config-airbnb-base-npm-15.0.0-802837dd26-38626bad2c.zip\node_modules\eslint-config-airbnb-base\rules\imports.js" and ".eslintrc.js » eslint-config-react-app".
    at mergePlugins (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:598:19)
    at createConfig (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:877:33)
    at CLIEngine.isPathIgnored (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\eslint-npm-8.28.0-a4b9cd416f-1b793486b2.zip\node_modules\eslint\lib\cli-engine\cli-engine.js:990:18)
    at CLIEngine.executeOnText (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\eslint-npm-8.28.0-a4b9cd416f-1b793486b2.zip\node_modules\eslint\lib\cli-engine\cli-engine.js:899:38)
    at ESLint.lintText (C:\Users\Home\Documents\Repository\ArcaRefresher\.yarn\cache\eslint-npm-8.28.0-a4b9cd416f-1b793486b2.zip\node_modules\eslint\lib\eslint\eslint.js:593:23)
    at c:\Users\Home\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:24378
    at E (c:\Users\Home\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:18748)
    at e.validate (c:\Users\Home\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:24337)
    at c:\Users\Home\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:220926
```
pnp 적용 이후 eslint-config-airbnb 와 eslint-config-react-app 간에 충돌 피드백이 계속 들어오고 있습니다.  
ESLint의 패키지 매니저를 yarn으로 직접 설정해도 발생하는걸로 봐서는 내부 호환성 문제가 있는거 같습니다.  
airbnb쪽을 포기하면 정상 동작하긴 합니다만 이쪽 관련 설정도 많이 이용하고 있던터라...

## 결론
pnp와 제로 인스톨 장점에 대해서는 잘 이해하고 있습니다만 개발환경에 차질이 생기는 부분은 너무 큰 상태입니다.
TypeScript 환경에서 정상 동작한다는 이야기가 있긴한데 자료도 별로 없고 당장 마이그레이션 해서 득이 되는것도 아니고 하니...
롤백을 검토하고 있습니다만 이 커밋 작업하시기도 했고 자주 fork 하시는거 감안해서 의견을 받아보고 하려고 합니다.

**Comment by green1052** [comment]
vscode에 yarn berry 관련 플러그인이 있는데
혹시 설치하셨나요?

**Comment by lekakid** [comment]
ZipFS 적용해도 동일합니다

**Comment by green1052** [comment]
https://yarnpkg.com/getting-started/editor-sdks

**Comment by green1052** [comment]
```yarn dlx @yarnpkg/sdks vscode```
해당 명령어로도 해결이 안되면 그냥 롤백해야할거 같네요

**Comment by green1052** [comment]
번외로 전에 말씀드렸던 swc-core 사용은 어떠신가요?

**Comment by lekakid** [comment]
리액트 프로젝트를 아예 새로 파서 yarn berry, pnp 구성까지 싹다 해봤을 때도 리액트 이외에 패키지는 전부 내부 타입이 안읽어집니다.
SDK 셋업도 다 해놨는데다가 리셋도 여러번 해봤습니다. 타입스크립트 프로젝트가 아니면 애초에 안 맞는게 아닌가 합니다.
이 외에 아시는 부분이 없다면 롤백하려합니다.
포크 후 패키지 설치 시간이 거슬리시는거라면 그냥 repository를 남겨놓고 pull 하시는게 낫지 않을까합니다.



SWC는 적용할 생각이 없습니다.

1. 릴리즈 빌드 시간은 1분 정도로 알고 있는데 50초 남짓을 단축하기 위해 개발 환경을 갈아엎는데 2~3일을 소모하고 싶지 않습니다. 업데이트가 그리 빈번한 편도 아니구요.
2. 디버그 테스트에 쓰는 빌드 시간은 10초도 걸리지 않습니다.
3. 디버그 테스트 환경에서 코드 변경을 하더라도 캐시된 코드를 사용하기 때문에 반영이 충분히 빠릅니다.
4. 릴리즈 빌드 및 배포는 깃허브 워크플로우를 통해 자동화되어서 시간 소모 문제가 영향이 없습니다.

**Comment by green1052** [comment]
확인했습니다.
